# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: Node install
  inputs:
    versionSource: 'spec'
    versionSpec: '14.x'

- task: Npm@1
  displayName: Npm install
  inputs:
    command: 'install'
    workingDir: '.'
- task: Npm@1
  displayName:  Npm Run and build
  inputs:
    command: 'custom'
    workingDir: '.'
    customCommand: 'run build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './dist/kickstart-angular'
    ArtifactName: 'Kickstart-dist'
    publishLocation: 'Container'
